"""baseline

Revision ID: 617d84857b66
Revises: 
Create Date: 2026-01-09 20:45:30.944973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617d84857b66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_metrics', 'post_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('posts_metrics', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts_metrics', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'posts_metrics', 'batch_runs', ['run_id'], ['id'])
    op.alter_column('subscribers', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'subscribers', 'batch_runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.alter_column('subscribers', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'posts_metrics', type_='foreignkey')
    op.drop_constraint(None, 'posts_metrics', type_='foreignkey')
    op.alter_column('posts_metrics', 'run_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts_metrics', 'post_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
