"""add subscriber_lifecycle_stints table

Revision ID: a408293b0a7c
Revises: d92118edd7ed
Create Date: 2026-09-22 15:45:59.651864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a408293b0a7c'
down_revision: Union[str, Sequence[str], None] = 'd92118edd7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_lifecycle_stints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=False),
    sa.Column('removed', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_lifecycle_stints_user_id'), 'subscriber_lifecycle_stints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_lifecycle_stints_user_id'), table_name='subscriber_lifecycle_stints')
    op.drop_table('subscriber_lifecycle_stints')
    # ### end Alembic commands ###
