"""add indexes on run_id and batch_run timestamp

Revision ID: bea9a5ea04f8
Revises: 617d84857b66
Create Date: 2026-09-10 13:02:35.216274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea9a5ea04f8'
down_revision: Union[str, Sequence[str], None] = '617d84857b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_batch_runs_timestamp'), 'batch_runs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_metrics_run_id'), 'posts_metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_subscribers_run_id'), 'subscribers', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_run_id'), table_name='subscribers')
    op.drop_index(op.f('ix_posts_metrics_run_id'), table_name='posts_metrics')
    op.drop_index(op.f('ix_batch_runs_timestamp'), table_name='batch_runs')
    # ### end Alembic commands ###
